steps:
   - name: 'gcr.io/cloud-builders/docker'
     args: ['build', '-t', 'f', 'predict.dockerfile', 'gcr.io/mlops-project-374509/predict.dockerfile', '.']
   - name: 'gcr.io/cloud-builders/docker'
     args: ['push', 'gcr.io/mlops-project-374509/predict.dockerfile']