program: src/models/train_model.py
method: bayes
metric:
  name: val_loss
  goal: minimize
parameters:
  lr:
    min: 0.0001
    max: 0.1
  epochs:
    min: 2
    max: 2
  batch_size:
    values: [16, 32, 64]
  seed:
    values: [42, 123]