name: Pre-commit CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Run Pre-commit
      uses: pre-commit/action@v3.0.1


    - name: Commit changes made by pre-commit
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git commit -am "Fix formatting issues by pre-commit" || echo "No changes to commit"
