name: "Run tests"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: 3.12
        os: ["ubuntu-latest", "windows-latest","macos-latest"]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r .github/workflows/requirements_tests.txt
        pip install ruff mypy
        pip list

    - name: Set PYTHONPATH for Windows
      if: runner.os == 'Windows'
      run: |
        $env:PYTHONPATH="$env:PYTHONPATH;$env:GITHUB_WORKSPACE\src"

    - name: Set PYTHONPATH for Unix-based systems
      if: runner.os != 'Windows'
      run: |
        export PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE/src

    - name: Test with pytest
      run: |
        pytest -v

    - name: Ruff check linting
      run: ruff check . --fix

    - name: Run mypy type-checking
      run: mypy src tests
